#ifndef LIB_GOOMUTILS_INCLUDE_GOOMUTILS_LOGGING_CONTROL_H_
#define LIB_GOOMUTILS_INCLUDE_GOOMUTILS_LOGGING_CONTROL_H_

namespace GOOM::UTILS
{

#ifndef FORCE_LOGGING
#define NO_LOGGING
#endif

} // namespace GOOM::UTILS
#endif
